--Paging SQL Server table

SELECT * FROM Groups ORDER BY GroupID OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY--retrieve 1-5
SELECT * FROM Groups ORDER BY GroupID OFFSET 5 ROWS FETCH NEXT 5 ROWS ONLY--retrieve 6-10
SELECT * FROM Groups ORDER BY GroupID OFFSET 1 ROWS FETCH NEXT 10 ROWS ONLY--retrieve 6-10


