create TRIGGER [dbo].[MMS_MT_REVISEFINANCEINFO] ON [dbo].[MMS_MT] 
AFTER UPDATE
AS
IF NOT ( UPDATE (MT_ACCFROM) OR UPDATE (MT_ACCTO) OR UPDATE (MT_FROMCOSTCENTER) OR UPDATE (MT_TOCOSTCENTER))
RETURN
SET NOCOUNT ON --TO PREVENT THE MESSAGE APPEARS FROM THE SYSTEM
--ROW CANNOT BE LOCATED SINCE IT WAS LAST UPDATED

BEGIN

UPDATE MMS_ITEMHIST SET ITEMHIST_ACCFROM = INSERTED.MT_ACCFROM,ITEMHIST_ACCTO = INSERTED.MT_ACCTO,ITEMHIST_CSFROM = INSERTED.MT_FROMCOSTCENTER,ITEMHIST_CSTO = INSERTED.MT_TOCOSTCENTER 
FROM INSERTED WHERE INSERTED.MT_CODE = ITEMHIST_TRANSNO AND ITEMHIST_TRANSTYPE = 'MT' 

SET NOCOUNT off
	
END
