create VIEW VWMMS_MTITEM AS 
SELECT MT_DBASEFROM as item_store,MTITEM_CODE as item_code,YEAR (MT_CONFRMDATE) AS item_YEAR,MONTH (MT_CONFRMDATE) AS item_MONTH,SUM(MTITEM_QUANTITY) as item_CONSUMPPERYEAR
FROM MMS_MT,MMS_MTITEM 
WHERE 
MMS_MT.MT_CODE = MMS_MTITEM.MTITEM_MT
AND 
MMS_MT.mt_FROMTOTYPE = 'S/D' 
and mt_mtstatus = 'C'
GROUP BY
MT_DBASEFROM,MTITEM_CODE ,YEAR (MT_CONFRMDATE),MONTH (MT_CONFRMDATE)

union
SELECT MT_DBASETO as item_store,MTITEM_CODE as item_code,YEAR (MT_CONFRMDATE) AS item_YEAR,MONTH (MT_CONFRMDATE) AS item_MONTH,SUM(MTITEM_QUANTITY*-1) as item_CONSUMPPERYEAR
FROM MMS_MT,MMS_MTITEM 
WHERE 
MMS_MT.MT_CODE = MMS_MTITEM.MTITEM_MT
AND 
MMS_MT.mt_FROMTOTYPE = 'D/S'
and mt_mtstatus = 'C'
GROUP BY
MT_DBASETO,MTITEM_CODE ,YEAR (MT_CONFRMDATE),MONTH (MT_CONFRMDATE)